version: "3.6"
services:
  elasticsearch:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    ports:
    - 9200:9200
  rat_kg:
    restart: always
    image: lupino/rat_kg:2019-10-08
    container_name: rat_kg
    volumes:
    - './data:/data/data'
    depends_on:
    - elasticsearch
    ports:
    - 8000:8000
